language: java
jdk:
 - openjdk8
script: ant build

addons:
  sonarcloud:
    organization: "federicox"
    token:
      secure: "0fab031ae26d420f4de4715c6f73cd77b1ed55b5"

script:
  - sonar-scanner